version: "3.8"

services:
  mongo:
    image: "bitnami/mongodb:latest"
    ports:
      - 27017:27017
    restart: always
    environment:
      - MONGODB_REPLICA_SET_MODE=primary
      - MONGODB_ROOT_USER=root
      - MONGODB_ROOT_PASSWORD=pass
      - MONGODB_REPLICA_SET_KEY=replicasetkey
    volumes:
      - "mongodb:/bitnami/mongodb"

volumes:
  mongodb:
